---
title: "covid-19 | CABA"
date: "Fecha: `r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    df_print: paged
    theme: lumen
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

# Librerias
```{r}
library("tidyverse")
library("ggplot2")
library("viridis")
library("hrbrthemes")
library("lubridate")
library("patchwork")

hrbrthemes::import_roboto_condensed()
```


# Dataset original
```{r Dataset}
df <- read.csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/salud/casos-covid-19/casos_covid19.csv",
         encoding = "UTF-8")

#glimpse(df)
```

# Busqueda 1
## Analisis y transformacion
```{r Analisis 1}
## busco los valores categoricos/unicos
unique(df$clasificacion) 
unique(df$genero)

sum(duplicated(df$id_caso)) ## busco por id_casos duplicados

df_sexo_tipo_contagio <- df %>%
  filter(
    !is.na(tipo_contagio),
    !is.na(genero)
  ) %>%
  group_by(genero, tipo_contagio) %>%
  count(genero, tipo_contagio, sort = T)

```

## Plot
```{r}
plot1 <- df_sexo_tipo_contagio %>%
  ggplot(aes(x = genero, fill = reorder(tipo_contagio, n), weight = n)) +
  geom_bar(position = "dodge") +
  theme(legend.position = "bottom") +
  coord_flip() +
  scale_fill_brewer(palette = "Set2") +
  labs(x = " ", y = " ", subtitle = "Total casos por tipo de contagio y genero", fill = "Tipo de contagio") +
  geom_text(aes(label = ifelse(count > 1500, ..count.., "")), stat = "count", position = position_dodge(width = 0.9), vjust = 0.25, hjust = 1.3, color = "#0F0F0F", size = 3.5) +
  geom_text(aes(label = ifelse(count < 1500, ..count.., "")), stat = "count", position = position_dodge(width = 0.9), vjust = 0.25, hjust = -0.4, color = "darkgray", size = 3.5) +
  theme_ipsum_rc()

plot1
```

# Busqueda 2
## Analisis y transformación
```{r}
df_trabajo_salud <- df %>%
  select(tipo_contagio, fecha_clasificacion, clasificacion, genero, edad) %>%
  mutate(
    fecha_clasificacion = dmy(gsub("\\:.*","", fecha_clasificacion)), ## transformo a fecha el formato era "ddMMyyyy:00:00:00.000000"
    mes = month(ymd(fecha_clasificacion), label = T),
    semana_anio = week(ymd(fecha_clasificacion)),
  ) %>% 
  filter(
    tipo_contagio == "Trabajador de la Salud",
    fecha_clasificacion >= "2020-03-01", ## desde marzo
    !is.na(genero) ## 2 casos, se desestiman
  ) %>% 
  count(mes, genero)

#glimpse(df_trabajo_salud)
```

## Plot2
```{r}
plot2 <- df_trabajo_salud %>%
  ggplot(aes(x = mes, y = n, fill = genero)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_brewer(palette = "Set2") +
  labs(x = " ", y = " ", subtitle = "Casos mensuales de trabajadores de la salud por género", fill = "Género") +
  geom_text(aes(label = ifelse(n > 100, n, "")), position = position_dodge(width = 0.9), vjust = 1.25, hjust = 0.5, color = "#0F0F0F", size = 3.5) +
  geom_text(aes(label = ifelse(n < 100, n, "")), position = position_dodge(width = 0.9), vjust = -1, hjust = 0.5, color = "darkgray", size = 3.5) +
  theme_ipsum_rc()

plot2

```

# Patchwork
```{r}
patchwork <- plot1 / plot2
patchwork + 
  plot_annotation(
  tag_levels = "A",
  title = "\nCasos covid-19 | CABA",
  caption = "Autor: Santiago Lator | tw: @SantiagoLator\n\nFuente: https://data.buenosaires.gob.ar/dataset/casos-covid-19\n",
  theme = theme(plot.title = element_text(size = 18),
                plot.caption = element_text(size = 10, hjust = 0))) &
  theme(text = element_text('Roboto Condensed'))
```
